# Generated by Django 4.1.4 on 2023-01-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("title",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
